import type { Metadata } from "next";
import Link from "next/link";
import type { Route } from "next";
import { BottomNav } from "@/components/BottomNav";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms of Service for Pick5 — a no-loss fantasy Premier League pool on Celo.",
};

const LAST_UPDATED = "23 May 2026";

export default function TermsPage() {
  return (
    <main className="min-h-dvh bg-[#08070D] text-white">
      <div className="mx-auto flex max-w-[640px] flex-col px-5 pt-5 pb-24">
        <header className="flex items-center justify-between">
          <Link
            href={"/" as Route}
            className="font-display text-2xl tracking-[0.2em] text-white"
          >
            PICK<span className="text-[#00DF7C]">5</span>
          </Link>
          <Link
            href={"/" as Route}
            className="text-xs text-white/50 underline-offset-4 hover:text-white/80 hover:underline"
          >
            ← Back
          </Link>
        </header>

        <section className="pt-6">
          <div className="text-[10px] font-medium uppercase tracking-[0.2em] text-[#00DF7C]">
            Legal
          </div>
          <h1 className="font-display mt-1 text-4xl leading-none tracking-tight">
            Terms of Service
          </h1>
          <p className="mt-2 text-xs text-white/40">
            Last updated: {LAST_UPDATED}
          </p>
        </section>

        <article className="mt-6 space-y-6 text-sm leading-6 text-white/75">
          <Section title="1. About Pick5">
            <p>
              Pick5 (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;) is a
              non-custodial fantasy Premier League pool deployed on Celo
              mainnet. Players deposit 1 USDT, pick 5 Premier League players
              for the final two matchweeks of the season (Gameweek 37 and 38),
              and compete for the entire prize pool generated by yield on Aave
              V3 plus a $10 USDT seed. By accessing{" "}
              <span className="text-white">pick5-beta.vercel.app</span> or
              interacting with the Pick5 smart contracts on Celo, you agree to
              these Terms.
            </p>
          </Section>

          <Section title="2. Eligibility">
            <ul className="list-disc space-y-1 pl-5">
              <li>You must be at least 18 years old.</li>
              <li>You must have a Celo-compatible self-custodial wallet.</li>
              <li>
                You confirm that participating in a no-loss fantasy pool is
                legal in your jurisdiction. You are responsible for compliance
                with your local laws, including tax obligations.
              </li>
            </ul>
          </Section>

          <Section title="3. How it works">
            <ul className="list-disc space-y-1 pl-5">
              <li>Deposit: 1 USDT on Celo mainnet.</li>
              <li>
                Pick 5 distinct Fantasy Premier League player IDs before the
                lock time.
              </li>
              <li>
                Lock time: 16 May 2026 14:00 UTC. After this moment the
                contract reverts new entries with <code>TournamentLocked()</code>.
              </li>
              <li>End time: 24 May 2026 19:00 UTC.</li>
              <li>Maximum 500 participants per pool.</li>
              <li>
                Scoring: total Fantasy Premier League points across Gameweeks
                37 and 38, as reported by the Premier League&apos;s FPL API.
              </li>
              <li>
                Winner: the participant with the highest total. In the event of
                a tie, the contract resolves the tie using an oracle-supplied
                random seed.
              </li>
              <li>
                Prize: the entire pool of Aave V3 yield generated by the
                combined deposits, plus the $10 USDT seed.
              </li>
              <li>
                Refund: every non-winning participant can call{" "}
                <code>withdrawDeposit()</code> after the tournament is
                finalized and receive their 1 USDT back. The winner also
                recovers their 1 USDT as part of their prize claim.
              </li>
            </ul>
          </Section>

          <Section title="4. Smart contracts">
            <p>
              Pick5 is governed entirely by the following immutable, verified
              contracts on Celo mainnet:
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-5 font-mono text-[12px] break-all">
              <li>
                Pick5Pool: 0xD587A5155F6d0792f0736C74644fe90180BBA6BA
              </li>
              <li>
                CoachAgent: 0x2cafF9A3c83292e2aB343204079B06FFD60a9046
              </li>
            </ul>
            <p className="mt-2">
              These contracts cannot be upgraded. Source code is published on
              GitHub and verified on Celoscan. The on-chain behavior of the
              contracts is the source of truth — these Terms describe it, but
              the contract takes precedence over any description.
            </p>
          </Section>

          <Section title="5. Pick5 Scout (AI Coach)">
            <p>
              We operate an autonomous AI agent (&quot;Pick5 Scout&quot;,
              registered as ERC-8004 Agent #9056 and Self Agent #104) that
              publishes a recommended 5-player lineup before each matchweek
              via an on-chain commit-reveal scheme. <strong className="text-white">The coach&apos;s
              picks are informational only and are not financial or sporting
              advice.</strong> Your lineup choices are entirely your own
              responsibility.
            </p>
          </Section>

          <Section title="6. Emergency provisions">
            <p>
              The Pick5Pool contract enforces fail-safes if the oracle does
              not submit scores:
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>
                <strong className="text-white">30 days after end time</strong>,
                any party may call <code>triggerEmergency()</code>, after
                which every participant can recover their 1 USDT via{" "}
                <code>emergencyUserWithdraw()</code>. No prize is paid in this
                scenario.
              </li>
              <li>
                <strong className="text-white">60 days after end time</strong>,
                if the emergency is still active and the pool has no remaining
                participants, the project owner may withdraw any residual
                balance.
              </li>
            </ul>
          </Section>

          <Section title="7. Risks">
            <p>By participating, you acknowledge the following risks:</p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>
                <strong className="text-white">Smart contract risk.</strong>{" "}
                Although the contracts have been reviewed, we make no warranty
                that they are free of bugs or vulnerabilities.
              </li>
              <li>
                <strong className="text-white">DeFi protocol risk.</strong>{" "}
                Your deposit is supplied to the Aave V3 USDT pool on Celo. If
                Aave or the underlying USDT token is exploited, frozen, or
                fails, recoverability is not guaranteed.
              </li>
              <li>
                <strong className="text-white">Data dependency.</strong>{" "}
                Scoring depends on the unofficial Fantasy Premier League
                public API. If that API changes, breaks, or restricts access,
                scoring may be delayed or the emergency provisions may need to
                be triggered.
              </li>
              <li>
                <strong className="text-white">Network risk.</strong> Celo
                network congestion, gas pricing, or downtime can delay
                transactions.
              </li>
              <li>
                <strong className="text-white">No guaranteed yield.</strong>{" "}
                The prize amount depends on Aave V3&apos;s variable USDT rate
                over the tournament period. We do not guarantee a minimum
                prize.
              </li>
            </ul>
          </Section>

          <Section title="8. Prohibited use">
            <p>You agree not to:</p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>
                Attempt to exploit, defraud, or interfere with the smart
                contracts or the operations of the AI Coach or oracle.
              </li>
              <li>
                Use multiple wallets to circumvent the one-entry-per-address
                rule (the contract enforces this at the wallet level).
              </li>
              <li>
                Use Pick5 in any way that violates applicable laws in your
                jurisdiction.
              </li>
            </ul>
          </Section>

          <Section title="9. Intellectual property">
            <p>
              Our smart contracts and application code are published on GitHub
              for transparency. All rights are reserved by the Pick5 project
              team unless an explicit open-source license file is added to the
              repository. You retain ownership of any data you publish to
              Pick5 (your chosen lineup, which is by nature public on-chain).
            </p>
          </Section>

          <Section title="10. Disclaimers">
            <p>
              Pick5 is provided{" "}
              <strong className="text-white">
                &quot;as is&quot; and &quot;as available&quot;, without
                warranties of any kind
              </strong>
              , express or implied, including merchantability, fitness for a
              particular purpose, and non-infringement. We do not warrant that
              the service will be uninterrupted, error-free, or secure.
            </p>
          </Section>

          <Section title="11. Limitation of liability">
            <p>
              To the maximum extent permitted by law, in no event shall Pick5,
              its operators, or its contributors be liable for any indirect,
              incidental, special, consequential, or exemplary damages arising
              from your use of the service, including but not limited to lost
              profits, lost tokens, or loss of access to funds. Our total
              liability shall in no case exceed the amount of your deposit
              (1 USDT).
            </p>
          </Section>

          <Section title="12. Termination">
            <p>
              We may discontinue the front-end interface (the website) at any
              time. The smart contracts are immutable and will continue to
              function independently. In particular, the emergency withdrawal
              paths described above remain available on-chain regardless of
              whether the website is accessible.
            </p>
          </Section>

          <Section title="13. Changes to these Terms">
            <p>
              We may revise these Terms from time to time. Material changes
              will be reflected by updating the &quot;Last updated&quot; date
              above. Your continued use of Pick5 after a change constitutes
              acceptance of the revised Terms.
            </p>
          </Section>

          <Section title="14. Governing law">
            <p>
              These Terms are governed by the laws of the Argentine Republic,
              without regard to conflict of law principles. Disputes will be
              resolved in the courts of the City of Buenos Aires, Argentina,
              subject to the consumer protection laws of your country of
              residence where applicable.
            </p>
          </Section>

          <Section title="15. Contact">
            <p>
              Questions about these Terms? Reach us on Telegram:{" "}
              <a
                href="https://t.me/pick5_support"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#00DF7C] underline-offset-4 hover:underline"
              >
                t.me/pick5_support
              </a>
              .
            </p>
          </Section>

          <p className="pt-4 text-center text-[11px] text-white/40">
            See also our{" "}
            <Link
              href={"/privacy" as Route}
              className="underline-offset-4 hover:text-white/70 hover:underline"
            >
              Privacy Policy
            </Link>
            .
          </p>
        </article>
      </div>
      <BottomNav />
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="font-display text-xl tracking-tight text-white">
        {title}
      </h2>
      <div className="mt-2 space-y-2">{children}</div>
    </section>
  );
}
